// Generates a reproducible Markdown metrics report at docs/ML_METRICS.md.
// Run: `node ml/report.js`. Numbers come straight from crossValidate()/benchmarkLatency()
// so the documented metrics can never silently drift from the code.

import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";
import { crossValidate, benchmarkLatency } from "./evaluate.js";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const pct = (x) => (x * 100).toFixed(1) + "%";

const cv = crossValidate({ k: 5 });
const lat = benchmarkLatency();
const total = cv.confusion.flat().reduce((a, b) => a + b, 0);

let md = `# Intent Classifier — Evaluation Report

> Auto-generated by \`node ml/report.js\`. Do not edit by hand.

**Model:** Multinomial Naive Bayes (Laplace smoothing) over word unigram+bigram and
character 3,4-gram features. Pure Node.js, zero runtime dependencies.

**Protocol:** 5-fold stratified cross-validation, deterministic seed = 42. Every one
of the ${total} labeled utterances is held out for testing exactly once.

## Headline metrics

| Metric | Value |
|---|---|
| Cross-validated accuracy | **${pct(cv.accuracy)}** (per-fold std ${pct(cv.accStd)}) |
| Macro precision | ${pct(cv.macro.precision)} |
| Macro recall | ${pct(cv.macro.recall)} |
| Macro F1 | ${pct(cv.macro.f1)} |
| Per-fold accuracy | ${cv.accPerFold.map(pct).join(", ")} |
| Inference latency (median) | ${lat.median.toFixed(3)} ms |
| Inference latency (p95) | ${lat.p95.toFixed(3)} ms |
| Classes | ${cv.labels.length} |
| Labeled samples | ${total} |

## Per-class metrics (aggregated over folds)

| Intent | Precision | Recall | F1 | Support |
|---|---|---|---|---|
`;
for (const label of cv.labels) {
  const c = cv.perClass[label];
  md += `| ${label} | ${pct(c.precision)} | ${pct(c.recall)} | ${pct(c.f1)} | ${c.support} |\n`;
}

md += `\n## Confusion matrix (rows = true, cols = predicted)\n\n`;
const short = cv.labels.map((l) => l.replace(/-/g, "").slice(0, 6));
md += `| true \\\\ pred | ${short.join(" | ")} |\n`;
md += `|${"---|".repeat(cv.labels.length + 1)}\n`;
cv.labels.forEach((label, i) => {
  md += `| ${short[i]} | ${cv.confusion[i].join(" | ")} |\n`;
});

const outPath = path.join(__dirname, "..", "..", "docs", "ML_METRICS.md");
fs.writeFileSync(outPath, md);
console.log("Wrote", outPath);
